import type { SkillDefinition, SkillId } from "../types.js";

export const skillCatalog: SkillDefinition[] = [
  {
    id: "antigravity.open",
    title: "Open Antigravity",
    description: "Launch Antigravity on the local Mac.",
    enabledByDefault: true,
    requiresApproval: false,
    approvalCategory: "app_launch",
    allowedModes: ["manual", "scheduled", "autonomy"],
    executorType: "mac_action",
  },
  {
    id: "antigravity.open_mission_url",
    title: "Open Antigravity Mission URL",
    description: "Launch Antigravity and open a mission URL via deep link.",
    enabledByDefault: true,
    requiresApproval: false,
    approvalCategory: "app_launch",
    allowedModes: ["manual", "scheduled", "autonomy"],
    executorType: "mac_action",
  },
  {
    id: "terminal.open",
    title: "Open Terminal",
    description: "Open the Terminal app on the local Mac.",
    enabledByDefault: true,
    requiresApproval: false,
    approvalCategory: "app_launch",
    allowedModes: ["manual", "scheduled", "autonomy"],
    executorType: "mac_action",
  },
  {
    id: "terminal.run_command",
    title: "Run Terminal Command",
    description: "Run a guarded command in workspace context.",
    enabledByDefault: true,
    requiresApproval: true,
    approvalCategory: "terminal_exec",
    allowedModes: ["manual", "scheduled", "autonomy"],
    executorType: "mac_action",
  },
  {
    id: "codex.run_task",
    title: "Run Codex Task",
    description: "Run a coding task through local Codex CLI.",
    enabledByDefault: true,
    requiresApproval: true,
    approvalCategory: "codex_exec",
    allowedModes: ["manual", "scheduled", "autonomy"],
    executorType: "codex_cli",
  },
  {
    id: "claude.run_task",
    title: "Run Claude Task",
    description: "Run a coding task through local Claude CLI.",
    enabledByDefault: true,
    requiresApproval: true,
    approvalCategory: "codex_exec",
    allowedModes: ["manual", "scheduled", "autonomy"],
    executorType: "claude_cli",
  },
  {
    id: "browser.embedded.open_tab",
    title: "Open Embedded Browser Tab",
    description: "Open URL in embedded browser workspace.",
    enabledByDefault: true,
    requiresApproval: false,
    approvalCategory: "app_launch",
    allowedModes: ["manual", "scheduled", "autonomy"],
    executorType: "browser",
  },
  {
    id: "browser.external.chrome.open",
    title: "Open URL in Chrome",
    description: "Open URL in external Chrome browser.",
    enabledByDefault: true,
    requiresApproval: true,
    approvalCategory: "browser_external",
    allowedModes: ["manual", "scheduled", "autonomy"],
    executorType: "browser",
  },
  {
    id: "x-social.run_endpoint",
    title: "Run X Endpoint",
    description: "Execute supported X social endpoint.",
    enabledByDefault: true,
    requiresApproval: true,
    approvalCategory: "write_command",
    allowedModes: ["manual", "scheduled", "autonomy"],
    executorType: "x_social",
  },
  {
    id: "code-workspace.exec",
    title: "Execute Workspace Command",
    description: "Execute guarded code workspace command.",
    enabledByDefault: true,
    requiresApproval: true,
    approvalCategory: "write_command",
    allowedModes: ["manual", "scheduled", "autonomy"],
    executorType: "code_workspace",
  },
];

const byId = new Map<SkillId, SkillDefinition>(skillCatalog.map((item) => [item.id, item]));

export const getSkillDefinition = (id: SkillId): SkillDefinition | undefined => byId.get(id);
